import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ signed: vi.fn(), local: vi.fn() }))
vi.mock('./objects', () => ({ signedOwnedObject: mocks.signed }))
vi.mock('@/features/assets/workstationHistory', () => ({ readHistoryImage: mocks.local }))
vi.mock('@/features/assets/historyOwner', () => ({ currentWorkstationHistoryOwner: () => 'a' }))
import { readOwnedImage, clearOwnedImageSession } from './ownedImages'
import { useUserStore } from '@/store/useUserStore'
const png = new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10])
const reference = (key = 'result') => ({ objectKey: key, url: `https://r2.test/${key}`, expiresAt: Date.now() + 60_000, mimeType: 'image/png' })
const response = () => new Response(png, { headers: { 'Content-Type': 'image/png' } })
beforeEach(() => {
  clearOwnedImageSession()
  mocks.local.mockReset().mockResolvedValue(undefined)
  mocks.signed.mockReset().mockResolvedValue({ url: 'https://r2.test/refreshed', expiresAt: Date.now() + 60_000 })
})
afterEach(() => { clearOwnedImageSession(); vi.unstubAllGlobals(); vi.useRealTimers() })

describe('共享图片读取', () => {
  it('并发预览、保存、下载共用一次 GET，后续复用同一 Blob', async () => {
    const fetch = vi.fn(async (url: string, init: RequestInit) => { void url; void init; return response() }); vi.stubGlobal('fetch', fetch)
    const [first, second] = await Promise.all([readOwnedImage(reference()), readOwnedImage(reference())])
    expect(first).toBe(second)
    expect(await readOwnedImage(reference())).toBe(first)
    expect(fetch).toHaveBeenCalledTimes(1)
    expect(fetch.mock.calls[0][1]).not.toHaveProperty('headers')
    expect(fetch.mock.calls[0][1]).toMatchObject({ credentials: 'omit' })
  })
  it('本地历史和已有 Blob 不请求网络，并纠正真实格式', async () => {
    const fetch = vi.fn(); vi.stubGlobal('fetch', fetch)
    mocks.local.mockResolvedValue(new Blob([png], { type: 'image/jpeg' }))
    expect((await readOwnedImage(reference())).type).toBe('image/png')
    clearOwnedImageSession()
    expect((await readOwnedImage({ blob: new Blob([png], { type: 'image/png' }) })).type).toBe('image/png')
    expect(fetch).not.toHaveBeenCalled()
  })
  it('单个使用方取消不影响另一个，共同取消中止底层下载', async () => {
    let finish!: () => void
    const fetch = vi.fn((_url, init: RequestInit) => new Promise<Response>((resolve, reject) => {
      finish = () => resolve(response())
      init.signal?.addEventListener('abort', () => reject(init.signal?.reason))
    })); vi.stubGlobal('fetch', fetch)
    const a = new AbortController(), b = new AbortController()
    const first = readOwnedImage(reference(), { signal: a.signal }).catch(error => error)
    const second = readOwnedImage(reference(), { signal: b.signal })
    await vi.waitFor(() => expect(fetch).toHaveBeenCalledTimes(1))
    a.abort(); expect(await first).toMatchObject({ name: 'AbortError' })
    expect(fetch.mock.calls[0][1].signal?.aborted).toBe(false)
    finish(); expect((await second).size).toBe(png.length)
    clearOwnedImageSession()
    const c = new AbortController()
    const third = readOwnedImage(reference(), { signal: c.signal }).catch(error => error)
    await vi.waitFor(() => expect(fetch).toHaveBeenCalledTimes(2))
    c.abort(); expect(await third).toMatchObject({ name: 'AbortError' })
    expect(fetch.mock.calls[1][1].signal?.aborted).toBe(true)
  })
  it('全局最多两个下载，排队后才检查签名', async () => {
    const releases: Array<() => void> = []
    const fetch = vi.fn(() => new Promise<Response>(resolve => releases.push(() => resolve(response())))); vi.stubGlobal('fetch', fetch)
    const reads = [readOwnedImage(reference('1')), readOwnedImage(reference('2')), readOwnedImage({ ...reference('3'), expiresAt: Date.now() + 20_000 })]
    await vi.waitFor(() => expect(fetch).toHaveBeenCalledTimes(2))
    expect(mocks.signed).not.toHaveBeenCalled()
    releases[0](); await vi.waitFor(() => expect(fetch).toHaveBeenCalledTimes(3))
    expect(mocks.signed).toHaveBeenCalledTimes(1)
    releases[1](); releases[2](); await Promise.all(reads)
  })
  it('网络异常或 403 刷新一次；失败不留缓存，下次可重试', async () => {
    const fetch = vi.fn().mockRejectedValueOnce(new TypeError('Failed to fetch')).mockResolvedValueOnce(new Response('', { status: 403 })).mockImplementation(async () => response())
    vi.stubGlobal('fetch', fetch)
    await expect(readOwnedImage(reference())).rejects.toMatchObject({ status: 403 })
    expect(mocks.signed).toHaveBeenCalledTimes(1)
    expect((await readOwnedImage(reference())).size).toBe(png.length)
    expect(fetch).toHaveBeenCalledTimes(3)
  })
  it('可读 404 不重试、不走代理；账号切换停止旧请求', async () => {
    const fetch = vi.fn().mockResolvedValueOnce(new Response('', { status: 404 })).mockImplementation((_url, init: RequestInit) => new Promise((_resolve, reject) => init.signal?.addEventListener('abort', () => reject(init.signal?.reason))))
    vi.stubGlobal('fetch', fetch)
    await expect(readOwnedImage(reference())).rejects.toThrow('结果对象不存在')
    expect(mocks.signed).not.toHaveBeenCalled()
    const old = readOwnedImage(reference()).catch(error => error)
    await vi.waitFor(() => expect(fetch).toHaveBeenCalledTimes(2))
    useUserStore.getState().setUser('b', 'free')
    expect(await old).toMatchObject({ name: 'AbortError' })
  })
  it('账号隔离，超过 32 项淘汰最早缓存', async () => {
    const fetch = vi.fn(async (url: string, init: RequestInit) => { void url; void init; return response() }); vi.stubGlobal('fetch', fetch)
    await readOwnedImage(reference(), { ownerId: 'a' }); await readOwnedImage(reference(), { ownerId: 'b' })
    expect(fetch).toHaveBeenCalledTimes(2)
    clearOwnedImageSession()
    for (let index = 0; index < 33; index++) await readOwnedImage(reference(String(index)))
    await readOwnedImage(reference('0'))
    expect(fetch).toHaveBeenCalledTimes(36)
  })
  it('60 秒超时也覆盖正文读取', async () => {
    vi.useFakeTimers()
    const fetch = vi.fn((_url, init: RequestInit) => Promise.resolve({ ok: true, status: 200, blob: () => new Promise((_resolve, reject) => init.signal?.addEventListener('abort', () => reject(init.signal?.reason))) }))
    vi.stubGlobal('fetch', fetch)
    const read = readOwnedImage(reference()).catch(error => error)
    await vi.advanceTimersByTimeAsync(60_001)
    expect(await read).toMatchObject({ status: 504 })
  })
  it('粗指针设备超过 64 MiB 的图片只由当前使用方持有，不进入长期缓存', async () => {
    vi.stubGlobal('matchMedia', () => ({ matches: true }))
    const fetch = vi.fn(async (url: string, init: RequestInit) => { void url; void init; return response() }); vi.stubGlobal('fetch', fetch)
    const blob = new Blob([png, new Uint8Array(64 * 1024 * 1024)], { type: 'image/png' })
    expect(await readOwnedImage({ ...reference(), blob })).toBe(blob)
    expect((await readOwnedImage(reference())).size).toBe(png.length)
    expect(fetch).toHaveBeenCalledTimes(1)
  })

  it('共享请求返回真实格式，每个使用方独立检查 MIME', async () => {
    const fetch = vi.fn(async (url: string, init: RequestInit) => { void url; void init; return response() }); vi.stubGlobal('fetch', fetch)
    const incorrect = readOwnedImage({ ...reference(), mimeType: 'image/jpeg' }).catch(error => error)
    const correct = readOwnedImage(reference())
    expect(await incorrect).toMatchObject({ status: 502 })
    expect((await correct).type).toBe('image/png')
    expect(fetch).toHaveBeenCalledTimes(1)
  })

})
