import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const css = readFileSync(resolve(process.cwd(), 'src/styles/global.css'), 'utf8')
const pageSource = readFileSync(resolve(process.cwd(), 'src/pages/FreeCanvas/index.tsx'), 'utf8')
const stageSource = readFileSync(resolve(process.cwd(), 'src/features/free-canvas/FreeCanvasStage.tsx'), 'utf8')
const addButtonSource = readFileSync(resolve(process.cwd(), 'src/pages/FreeCanvas/CanvasAddImageButton.tsx'), 'utf8')
const textPanel = readFileSync(resolve(process.cwd(), 'src/features/free-canvas/generation/GenerationPanel.tsx'), 'utf8')
const derivedPanel = readFileSync(resolve(process.cwd(), 'src/features/free-canvas/generation/DerivedGenerationPanel.tsx'), 'utf8')

function block(selector: string, source = css) {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  return source.match(new RegExp(`${escaped}\\s*\\{([^}]*)\\}`))?.[1] ?? ''
}

describe('自由画布面板布局', () => {
  it('文生图、文生视频和图片派生面板共用可滚动卡片', () => {
    expect(pageSource).toContain('CanvasAddImageButton')
    expect(pageSource).not.toContain('free-canvas-page-actions')
    expect(pageSource).not.toContain('{scene.width} × {scene.height}')
    expect(textPanel).toContain('className="free-canvas-generation-panel"')
    expect(derivedPanel).toContain('className="free-canvas-generation-panel free-canvas-derived-panel"')
    expect(textPanel.indexOf('<VideoCreditEstimate')).toBeLessThan(textPanel.indexOf('className="free-canvas-generate"'))
    expect(derivedPanel.indexOf('<VideoCreditEstimate')).toBeLessThan(derivedPanel.indexOf('className="free-canvas-generate"'))
  })

  it('宽屏下提示、积分和生成按钮留在卡片内并在面板里滚动', () => {
    const panel = block('.free-canvas-generation-panel')
    expect(panel).toMatch(/min-height:\s*0/)
    expect(panel).toMatch(/max-height:\s*100%/)
    expect(panel).toMatch(/overflow-x:\s*hidden/)
    expect(panel).toMatch(/overflow-y:\s*auto/)
  })

  it('窄屏工具栏换行，画布自适应，面板堆到画布下方且宽度 100%', () => {
    const narrow = css.slice(css.lastIndexOf('@media (max-width: 720px)'))
    expect(block('.free-canvas-page', narrow)).toMatch(/height:\s*auto/)
    expect(block('.free-canvas-page-header', narrow)).toMatch(/flex-direction:\s*row/)
    expect(block('.free-canvas-workspace', narrow)).toMatch(/flex-direction:\s*column/)
    expect(block('.free-canvas-stage', narrow)).toMatch(/width:\s*100%/)
    expect(block('.free-canvas-stage', narrow)).toMatch(/max-width:\s*100%/)
    expect(block('.free-canvas-toolbar', narrow)).toMatch(/flex-wrap:\s*wrap/)
    const panel = block('.free-canvas-generation-panel', narrow)
    expect(panel).toMatch(/width:\s*100%/)
    expect(panel).toMatch(/max-height:\s*none/)
    expect(panel).toMatch(/overflow:\s*visible/)
    expect(block('.free-canvas-help', narrow)).toMatch(/display:\s*none/)
    expect(block('.free-canvas-add-label', narrow)).toMatch(/display:\s*none/)
    expect(block('.free-canvas-page-header')).toMatch(/flex-wrap:\s*wrap/)
    expect(block('.free-canvas-page')).toMatch(/max-width:\s*100%/)
    expect(pageSource).not.toContain('ProjectToolbar')
    expect(pageSource).not.toContain('project-toolbar')
    expect(pageSource).toContain('CloudToolbar')
    expect(block('.canvas-project-name-text')).toMatch(/text-overflow:\s*ellipsis/)
    expect(block('.project-actions-dropdown')).toMatch(/z-index:\s*40/)
    expect(css).toMatch(/@container app-header \(max-width: 560px\)[\s\S]*?display:\s*none/)
    expect(css).toMatch(/\.tool-switcher\s*\{[^}]*scrollbar-width:\s*none/)
    expect(css).toMatch(/\.tool-switcher\s*\{[^}]*overflow-x:\s*auto/)
    expect(css).toMatch(/\.tool-switcher::-webkit-scrollbar\s*\{[^}]*display:\s*none/)
    expect(css).toMatch(/\.tool-switcher-fade\.is-visible\s*\{[^}]*opacity:\s*1/)
    expect(css).toMatch(/\.app-shell,\s*\.app-shell-main,\s*\.app-main-content\s*\{[^}]*min-width:\s*0/)
  })

  it('添加图片浮在画布内，操作提示变淡并可在首次交互后隐藏', () => {
    expect(addButtonSource).toContain('本地上传')
    expect(addButtonSource).toContain('从我的资产')
    expect(addButtonSource).toContain('aria-label="添加图片"')
    expect(addButtonSource).toContain('title="添加图片"')
    expect(stageSource).toContain('free-canvas-stage-chrome')
    expect(stageSource).toContain('is-dismissed')
    expect(stageSource).toContain('dismissHintRef.current()')
    const chrome = block('.free-canvas-stage-chrome')
    expect(chrome).toMatch(/position:\s*absolute/)
    expect(chrome).toMatch(/z-index:\s*3/)
    expect(chrome).toMatch(/pointer-events:\s*none/)
    expect(chrome).toMatch(/justify-content:\s*space-between/)
    expect(Number(chrome.match(/z-index:\s*(\d+)/)?.[1])).toBeLessThan(20)
    const help = block('.free-canvas-help')
    expect(help).toMatch(/opacity:\s*0\.62/)
    expect(help).toMatch(/pointer-events:\s*auto/)
    expect(block('.free-canvas-help.is-dismissed')).toMatch(/opacity:\s*0/)
    expect(block('.free-canvas-add-image')).toMatch(/pointer-events:\s*auto/)
    const toolbar = block('.free-canvas-toolbar')
    expect(toolbar).toMatch(/z-index:\s*2/)
    expect(toolbar).toMatch(/bottom:\s*18px/)
    expect(toolbar).toMatch(/left:\s*50%/)
    expect(pageSource).toContain('className="free-canvas-page-header page-tab-row"')
    expect(block(':root')).toMatch(/--page-tab-gap:\s*16px/)
    expect(block('.page-tab-row')).toMatch(/margin-bottom:\s*var\(--page-tab-gap\)/)
    expect(block('.free-canvas-page-header')).not.toMatch(/margin-bottom/)
  })

  it('生成声音使用不拉伸的标准开关，主生成按钮保持主按钮高度', () => {
    const settings = readFileSync(resolve(process.cwd(), 'src/features/free-canvas/generation/VideoGenerationSettings.tsx'), 'utf8')
    expect(settings).toContain('free-canvas-switch-field')
    expect(settings).toContain('<Switch')
    const row = block('.free-canvas-switch-field')
    expect(row).toMatch(/flex-direction:\s*row/)
    expect(row).toMatch(/align-items:\s*center/)
    expect(row).toMatch(/justify-content:\s*space-between/)
    const toggle = block('.free-canvas-switch-field > .ant-switch')
    expect(toggle).toMatch(/flex:\s*0 0 auto/)
    expect(toggle).toMatch(/width:\s*auto/)
    expect(textPanel).toContain('className="free-canvas-generate"')
    expect(derivedPanel).toContain('className="free-canvas-generate"')
    expect(block('.free-canvas-generate.ant-btn')).toMatch(/flex-shrink:\s*0/)
  })
})
